apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  frontend-deployment-autoscaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50