apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: frontend-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http