apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: backend-app
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http